### ISSUE TITLE
Mismatch between actual versions of Microsoft.Azure.Storage.* libraries used and those reported by NuGet.

### ISSUE THREAD

**Issue by older** [Azure/azure-storage-net-data-movement#270]
Somewhere between versions 2.0.1 and 2.0.3 NuGet references to Microsoft.Azure.Storage.* libraries were updated to 11.2.2.0 while .nuspec file still says that [version 11.2.0 is used](https://github.com/Azure/azure-storage-net-data-movement/blob/master/tools/nupkg/Microsoft.Azure.Storage.DataMovement.nuspec#L28). When I update my project to 2.0.3 I get the following error:

```
error CS1705: Assembly 'Microsoft.Azure.Storage.DataMovement'
with identity 'Microsoft.Azure.Storage.DataMovement, Version=2.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
uses 'Microsoft.Azure.Storage.Blob, Version=11.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
which has a higher version than referenced assembly 'Microsoft.Azure.Storage.Blob'
with identity 'Microsoft.Azure.Storage.Blob, Version=11.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by mgroetan** [comment]
On the slightly off-topic comment about a migration route towards the new "Azure" series, I'm specifically looking for an alternative to the "TransferManager" class. I'd deeply appreciate if anyone in the team could point me in the right direction.

**Comment by amnguye** [comment]
We are looking upping the version of Microsoft.Azure.Storage.* libraries soon and making another release of the DataMovement library to resolve this problem soon.

**Comment by amnguye** [comment]
We will also look to upgrade to 11.2.3 due to a major fix made in the Microsoft.Azure.Storage.Blob, Files, and Common package where there was a race condition in UploadStream which the DataMovement library takes advantage of.

**Comment by amnguye** [comment]
Please kindly upgrade to 2.0.4 to avoid the mismatch error of the `Microsoft.Azure.Storage.*` libraries. Also we've upgraded to 11.2.3 of the `Microsoft.Azure.Storage.Common`, `Blob`, and `File` to avoid the race condition when uploading streams.
